apiVersion: lambda.services.k8s.aws/v1alpha1
kind: Function
metadata:
  annotations:
    services.k8s.aws/region: {{ .Values.region }}
    {{- with .Values.annotations }}
      {{- toYaml . | nindent 4 }}
    {{- end }}
  name: {{ include "ack-lambda-function.fullname" . }}
  labels:
    {{- include "ack-lambda-function.labels" . | nindent 4 }}
spec:
  code:
    imageURI: "{{ .Values.image.repo }}:{{ .Values.image.tag }}"
  description: {{ .Values.description }}
  name: {{ include "ack-lambda-function.fullname" . }}
  packageType: Image
  publish: false
  role: {{ .Values.iamRole }}