apiVersion: lambda.services.k8s.aws/v1alpha1
kind: Version
metadata:
  annotations:
    services.k8s.aws/region: {{ .Values.region }}
    {{- with .Values.annotations }}
      {{- toYaml . | nindent 4 }}
    {{- end }}
  {{ $randomStr := (randAlphaNum 5 | lower) }}
  {{- if $randomStr }}
  name: {{ include "ack-lambda-version.fullname" . }}-{{ $randomStr }}
  {{- end }}
  labels:
    {{- include "ack-lambda-version.labels" . | nindent 4 }}
spec:
  functionRef: 
    from: 
      name: {{ .Values.functionName }}
      namespace: {{ .Release.Namespace }}
  {{- if .Values.revisionID }}
  revisionID: {{ .Values.revisionID }}
  {{- end }}
---
apiVersion: v1
kind: ConfigMap
metadata:
  annotations:
    {{- with .Values.annotations }}
      {{- toYaml . | nindent 4 }}
    {{- end }}
  name: {{ include "ack-lambda-version.fullname" . }}-cm
data:
  {{- if $randomStr }}
  versionName: {{ include "ack-lambda-version.fullname" . }}-{{ $randomStr }}
  {{- end }}